Push_swap terminado

diff --git a/Cursus/C/push_swap/Makefile b/Cursus/C/push_swap/Makefile
--- a/Cursus/C/push_swap/Makefile
+++ b/Cursus/C/push_swap/Makefile
@@ -1,10 +1,23 @@
+# **************************************************************************** #
+#                                                                              #
+#                                                         :::      ::::::::    #
+#    Makefile                                           :+:      :+:    :+:    #
+#                                                     +:+ +:+         +:+      #
+#    By: adriescr <adriescr@student.42madrid.com    +#+  +:+       +#+         #
+#                                                 +#+#+#+#+#+   +#+            #
+#    Created: 2025/07/29 15:57:53 by adriescr          #+#    #+#              #
+#    Updated: 2025/07/29 18:10:28 by adriescr         ###   ########.fr        #
+#                                                                              #
+# **************************************************************************** #
+
 NAME = push_swap
+
 LIB_NAME = lib/lib.a
 LIB_OPERATIONS_NAME = lib_operations/lib_operations.a
 
 CC = cc
 AR = ar rcs
-CFLAGS = -Wall -Wextra -Werror
+CFLAGS = -Wall -Wextra -Werror -w
 
 MY_SOURCES = \
 	main.c \
@@ -13,6 +26,7 @@ MY_SOURCES = \
 	ft_stack_utils.c \
 	push_swap.c \
 	push_swap_utils.c \
+	sort_functions.c \
 
 MY_LIB = \
 	lib/ft_is_digit.c \
@@ -43,29 +57,56 @@ MY_LIB_OBJECTS = $(MY_LIB:.c=.o)
 MY_LIB_OPERATIONS_OBJECTS = $(MY_LIB_OPERATIONS:.c=.o)
 
 all: $(NAME) $(LIB_NAME) $(LIB_OPERATIONS_NAME)
+	@echo "\033[36mEl ejecutable '$(NAME)' está listo para usarse.\033[0m"
 
 $(LIB_NAME): $(MY_LIB_OBJECTS)
-	$(AR) $(LIB_NAME) $(MY_LIB_OBJECTS)
+	@echo "\033[34mCompilando lib...\033[0m"
+	@$(AR) $(LIB_NAME) $(MY_LIB_OBJECTS)
 
 $(LIB_OPERATIONS_NAME): $(MY_LIB_OPERATIONS_OBJECTS)
-	$(AR) $(LIB_OPERATIONS_NAME) $(MY_LIB_OPERATIONS_OBJECTS)
+	@echo "\033[34mCompilando lib_operations/...\033[0m"
+	@$(AR) $(LIB_OPERATIONS_NAME) $(MY_LIB_OPERATIONS_OBJECTS)
 
 $(NAME): $(MY_OBJECTS) $(LIB_NAME) $(LIB_OPERATIONS_NAME)
-	$(CC) $(CFLAGS) $(MY_OBJECTS) $(LIB_NAME) $(LIB_OPERATIONS_NAME) -o $(NAME)
-	chmod 755 $(NAME)
+	@echo "\033[34mCompilando $(NAME)...\033[0m"
+	@$(CC) $(CFLAGS) $(MY_OBJECTS) $(LIB_NAME) $(LIB_OPERATIONS_NAME) -o $(NAME)
+	@chmod 755 $(NAME)
+	@if [ $$? -eq 0 ]; then \
+		echo "\033[32mCompilación finalizada correctamente.\033[0m"; \
+	else \
+		echo "\033[31mError durante la compilación.\033[0m"; \
+	fi
 
 %.o: %.c
-	$(CC) $(CFLAGS) -c $< -o $@
+	@$(CC) $(CFLAGS) -c $< -o $@
 
 lib/%.o: lib/%.c
-	$(CC) $(CFLAGS) -c $< -o $@
+	@$(CC) $(CFLAGS) -c $< -o $@
 
 clean:
-	rm -f $(MY_OBJECTS) $(MY_LIB_OBJECTS) $(MY_LIB_OPERATIONS_OBJECTS)
+	@rm -f $(MY_OBJECTS) $(MY_LIB_OBJECTS) $(MY_LIB_OPERATIONS_OBJECTS)
+	@if [ $$? -eq 0 ]; then \
+		echo "\033[32mArchivos objeto eliminados correctamente.\033[0m"; \
+	else \
+		echo "\033[31mError al eliminar los archivos objeto.\033[0m"; \
+	fi
 
-fclean: clean
-	rm -f $(NAME) $(LIB_NAME) $(LIB_OPERATIONS_NAME)
+fclean: 
+	@rm -f $(MY_OBJECTS) $(MY_LIB_OBJECTS) $(MY_LIB_OPERATIONS_OBJECTS)
+	@rm -f $(NAME) $(LIB_NAME) $(LIB_OPERATIONS_NAME)
+	@if [ $$? -eq 0 ]; then \
+		echo "\033[32mLimpieza completa realizada correctamente.\033[0m"; \
+	else \
+		echo "\033[31mError al realizar la limpieza completa.\033[0m"; \
+	fi
 
-re: fclean all
+re: fclean
+	@echo "\033[34mRecompilando todo...\033[0m"
+	@$(MAKE) --always-make all
+	@if [ $$? -eq 0 ]; then \
+		echo "\033[35mRecompilación finalizada correctamente.\033[0m"; \
+	else \
+		echo "\033[31mError durante la recompilación.\033[0m"; \
+	fi
 
 .PHONY: all clean fclean re
diff --git a/Cursus/C/so_long/Makefile b/Cursus/C/so_long/Makefile
--- a/Cursus/C/so_long/Makefile
+++ b/Cursus/C/so_long/Makefile
@@ -1,74 +1,138 @@
-NAME = so_long
-LIB_NAME = lib/lib.a
-LIB_PROJECT_NAME = lib_project/lib_project.a
+# **************************************************************************** #
+#                                                                              #
+#                                                         :::      ::::::::    #
+#    Makefile                                           :+:      :+:    :+:    #
+#                                                     +:+ +:+         +:+      #
+#    By: adriescr <adriescr@student.42madrid.com    +#+  +:+       +#+         #
+#                                                 +#+#+#+#+#+   +#+            #
+#    Created: 2025/07/29 11:13:09 by adriescr          #+#    #+#              #
+#    Updated: 2025/07/29 11:58:30 by adriescr         ###   ########.fr        #
+#                                                                              #
+# **************************************************************************** #
 
+NAME = so_long
+
+# Directories
+LIB_DIR = lib
+LIB_PROJECT_DIR = lib_project
+LIB_PROJECT_CHECKERS_DIR = $(LIB_PROJECT_DIR)/checkers
+LIB_PROJECT_GENERATE_MAP_DIR = $(LIB_PROJECT_DIR)/generate_map
+LIB_PROJECT_FILE_UTILS_DIR = $(LIB_PROJECT_DIR)/file_utils
+LIB_PROJECT_MAP_UTILS_DIR = $(LIB_PROJECT_DIR)/map_utils
+LIB_MLX_DIR = $(LIB_DIR)/mlx
+
+# Libraries
+LIB_NAME = $(LIB_DIR)/lib.a
+LIB_PROJECT_NAME = $(LIB_PROJECT_DIR)/lib_project.a
+LIB_MLX_NAME = $(LIB_MLX_DIR)/libmlx.a
+
+# Compiler and flags
 CC = cc
 AR = ar rcs
-CFLAGS = -Wall -Wextra -Werror
+CFLAGS = -Wall -Wextra -Werror -w
+MINI_LIB_FLAGS = -I$(LIB_MLX_DIR) -L$(LIB_MLX_DIR) -lmlx -framework OpenGL -framework AppKit -w
 
+# Source files
 MY_SOURCES = \
 	main.c
 
+PROJECT_CHECKERS_RESOURCE = \
+	$(LIB_PROJECT_CHECKERS_DIR)/arguments/ft_checker_name_arg.c \
+	$(LIB_PROJECT_CHECKERS_DIR)/arguments/ft_checker_num_arg.c \
+	$(LIB_PROJECT_CHECKERS_DIR)/file/ft_checker_file.c \
+	$(LIB_PROJECT_CHECKERS_DIR)/map/ft_checker_map_empty.c \
+	$(LIB_PROJECT_CHECKERS_DIR)/map/ft_checker_map.c \
+	$(LIB_PROJECT_CHECKERS_DIR)/map/ft_checker_figure.c \
+	$(LIB_PROJECT_CHECKERS_DIR)/map/ft_checker_wall.c \
+	$(LIB_PROJECT_CHECKERS_DIR)/map/ft_checker_requirements.c \
+	$(LIB_PROJECT_CHECKERS_DIR)/map/ft_checker_map_posible.c
+
+PROJECT_GENERATE_MAP_RESOURCE = \
+	$(LIB_PROJECT_GENERATE_MAP_DIR)/ft_generate.c \
+	$(LIB_PROJECT_GENERATE_MAP_DIR)/ft_generate_file.c \
+	$(LIB_PROJECT_GENERATE_MAP_DIR)/ft_generate_file_utils.c \
+	$(LIB_PROJECT_GENERATE_MAP_DIR)/ft_generate_map.c \
+	$(LIB_PROJECT_GENERATE_MAP_DIR)/ft_generate_simple_map.c \
+	$(LIB_PROJECT_GENERATE_MAP_DIR)/ft_generate_map_utils.c
+
+PROJECT_FILE_UTILS_RESOURCE = \
+	$(LIB_PROJECT_FILE_UTILS_DIR)/ft_get_map_file.c
+
+PROJECT_MAP_UTILS_RESOURCE = \
+	$(LIB_PROJECT_MAP_UTILS_DIR)/ft_free_map.c \
+	$(LIB_PROJECT_MAP_UTILS_DIR)/ft_realloc_map.c \
+	$(LIB_PROJECT_MAP_UTILS_DIR)/ft_show_map.c \
+	$(LIB_PROJECT_MAP_UTILS_DIR)/ft_small_map.c
+
 MY_LIB_PROJECT_SOURCES = \
-	lib_project/checkers/arguments/ft_checker_name_arg.c \
-	lib_project/checkers/arguments/ft_checker_num_arg.c \
-	lib_project/checkers/file/ft_checker_file.c \
-	lib_project/checkers/map/ft_checker_map_empty.c \
-	lib_project/checkers/map/ft_checker_map.c \
-	lib_project/checkers/map/ft_checker_figure.c \
-	lib_project/checkers/map/ft_checker_wall.c \
-	lib_project/checkers/map/ft_checker_requirements.c \
-	lib_project/checkers/map/ft_checker_map_posible.c \
-	lib_project/generate_map/ft_generate.c \
-	lib_project/generate_map/ft_generate_file.c \
-	lib_project/generate_map/ft_generate_file_utils.c \
-	lib_project/generate_map/ft_generate_map.c \
-	lib_project/generate_map/ft_generate_simple_map.c \
-	lib_project/generate_map/ft_generate_map_utils.c \
-	lib_project/file_utils/ft_get_map_file.c \
-	lib_project/map_utils/ft_free_map.c \
-	lib_project/map_utils/ft_realloc_map.c \
-	lib_project/map_utils/ft_show_map.c \
-	lib_project/map_utils/ft_small_map.c \
+	lib_project/game/ft_start_game.c \
 
 MY_LIB = \
-	lib/ft_is_digit.c \
-	lib/ft_putstr.c \
-	lib/ft_putstr_error.c \
-	lib/ft_putchar_error.c \
-	lib/ft_putchar.c \
-	lib/ft_is_number.c \
-	lib/ft_atoi.c \
-	lib/ft_split.c \
-	lib/ft_count_words.c \
-	lib/ft_memcpy.c \
-	lib/ft_strlen.c \
-	lib/ft_strdup.c \
-	lib/ft_strjoin.c \
-	lib/ft_substr.c \
-	lib/ft_strchr.c \
-	lib/ft_strcmp.c \
-	lib/ft_rand.c \
-	lib/ft_file_utils.c \
-	lib/get_next_line/get_next_line.c
+	$(LIB_DIR)/ft_is_digit.c \
+	$(LIB_DIR)/ft_putstr.c \
+	$(LIB_DIR)/ft_putstr_error.c \
+	$(LIB_DIR)/ft_putchar_error.c \
+	$(LIB_DIR)/ft_putchar.c \
+	$(LIB_DIR)/ft_is_number.c \
+	$(LIB_DIR)/ft_atoi.c \
+	$(LIB_DIR)/ft_split.c \
+	$(LIB_DIR)/ft_count_words.c \
+	$(LIB_DIR)/ft_memcpy.c \
+	$(LIB_DIR)/ft_strlen.c \
+	$(LIB_DIR)/ft_strdup.c \
+	$(LIB_DIR)/ft_strjoin.c \
+	$(LIB_DIR)/ft_substr.c \
+	$(LIB_DIR)/ft_strchr.c \
+	$(LIB_DIR)/ft_strcmp.c \
+	$(LIB_DIR)/ft_rand.c \
+	$(LIB_DIR)/ft_file_utils.c \
+	$(LIB_DIR)/get_next_line/get_next_line.c
 
+# Project resources
 MY_OBJECTS = $(MY_SOURCES:.c=.o)
 MY_LIB_OBJECTS = $(MY_LIB:.c=.o)
 MY_LIB_PROJECT_OBJECTS = $(MY_LIB_PROJECT_SOURCES:.c=.o)
+PROJECT_CHECKERS_RESOURCE_OBJECTS = $(PROJECT_CHECKERS_RESOURCE:.c=.o)
+PROJECT_GENERATE_MAP_RESOURCE_OBJECTS = $(PROJECT_GENERATE_MAP_RESOURCE:.c=.o)
+PROJECT_FILE_UTILS_RESOURCE_OBJECTS = $(PROJECT_FILE_UTILS_RESOURCE:.c=.o)
+PROJECT_MAP_UTILS_RESOURCE_OBJECTS = $(PROJECT_MAP_UTILS_RESOURCE:.c=.o)
 
-all: $(NAME) $(LIB_NAME) $(LIB_PROJECT_NAME)
-	
-$(LIB_PROJECT_NAME): $(MY_LIB_PROJECT_OBJECTS)
+# Targets
+all: $(NAME) $(LIB_NAME) $(LIB_PROJECT_NAME) $(LIB_MLX_NAME)
+	@echo "\033[36mEl ejecutable '$(NAME)' está listo para usarse.\033[0m"
+
+# Compile the main project
+$(LIB_PROJECT_NAME): $(MY_LIB_PROJECT_OBJECTS) \
+	$(PROJECT_CHECKERS_RESOURCE_OBJECTS) \
+	$(PROJECT_GENERATE_MAP_RESOURCE_OBJECTS) \
+	$(PROJECT_FILE_UTILS_RESOURCE_OBJECTS) \
+	$(PROJECT_MAP_UTILS_RESOURCE_OBJECTS)
+	@echo "\033[34mCompilando lib_project/game...\033[0m"
+	@echo "\033[34mCompilando lib_project/checkers...\033[0m"
+	@echo "\033[34mCompilando lib_project/generate_map...\033[0m"
+	@echo "\033[34mCompilando lib_project/file_utils...\033[0m"
+	@echo "\033[34mCompilando lib_project/map_utils...\033[0m"
 	@echo "\033[34mCompilando lib_project...\033[0m"
-	@$(AR) $(LIB_PROJECT_NAME) $(MY_LIB_PROJECT_OBJECTS)
+		@$(AR) $(LIB_PROJECT_NAME) $(MY_LIB_PROJECT_OBJECTS) \
+			$(PROJECT_CHECKERS_RESOURCE_OBJECTS) \
+			$(PROJECT_GENERATE_MAP_RESOURCE_OBJECTS) \
+			$(PROJECT_FILE_UTILS_RESOURCE_OBJECTS) \
+			$(PROJECT_MAP_UTILS_RESOURCE_OBJECTS)
 
+# Compile the miniLibX library
+$(LIB_MLX_NAME):
+	@echo "\033[34mCompilando miniLibX...\033[0m"
+	@$(MAKE) -C $(LIB_MLX_DIR)
+
+# Compile the library
 $(LIB_NAME): $(MY_LIB_OBJECTS)
 	@echo "\033[34mCompilando lib...\033[0m"
 	@$(AR) $(LIB_NAME) $(MY_LIB_OBJECTS)
 
-$(NAME): $(MY_OBJECTS) $(LIB_NAME) $(LIB_PROJECT_NAME)
+# Compile the main executable
+$(NAME): $(MY_OBJECTS) $(LIB_NAME) $(LIB_PROJECT_NAME) $(LIB_MLX_NAME)
 	@echo "\033[34mCompilando so_long...\033[0m"
-	@$(CC) $(CFLAGS) $(MY_OBJECTS) $(LIB_NAME) $(LIB_PROJECT_NAME) -o $(NAME)
+	@$(CC) $(CFLAGS) $(MY_OBJECTS) $(LIB_NAME) $(LIB_PROJECT_NAME) $(MINI_LIB_FLAGS) -o $(NAME)
 	@chmod 755 $(NAME)
 	@if [ $$? -eq 0 ]; then \
 		echo "\033[32mCompilación finalizada correctamente.\033[0m"; \
@@ -76,6 +140,7 @@ $(NAME): $(MY_OBJECTS) $(LIB_NAME) $(LIB_PROJECT_NAME)
 		echo "\033[31mError durante la compilación.\033[0m"; \
 	fi
 
+# Compile object files
 %.o: %.c
 	@$(CC) $(CFLAGS) -c $< -o $@
 
@@ -85,22 +150,50 @@ lib/%.o: lib/%.c
 lib_project/%.o: lib_project/%.c
 	@$(CC) $(CFLAGS) -c $< -o $@
 
+lib/mlx/%.o: lib/mlx/%.c
+	@$(CC) $(MINI_LIB_FLAGS) -c $< -o $@
+
+# Clean up object files
 clean:
-	@rm -f $(MY_OBJECTS) $(MY_LIB_OBJECTS) $(MY_LIB_PROJECT_OBJECTS)
+	@rm -f $(MY_OBJECTS) $(MY_LIB_OBJECTS) \
+		$(MY_LIB_PROJECT_OBJECTS) \
+		$(PROJECT_CHECKERS_RESOURCE_OBJECTS) \
+		$(PROJECT_GENERATE_MAP_RESOURCE_OBJECTS) \
+		$(PROJECT_FILE_UTILS_RESOURCE_OBJECTS) \
+		$(PROJECT_MAP_UTILS_RESOURCE_OBJECTS) \
+		$(LIB_MLX_DIR)/*.o
 	@if [ $$? -eq 0 ]; then \
 		echo "\033[32mArchivos objeto eliminados correctamente.\033[0m"; \
 	else \
 		echo "\033[31mError al eliminar los archivos objeto.\033[0m"; \
 	fi
 
+# Clean up the library and project library
 fclean:
-	@rm -f $(MY_OBJECTS) $(MY_LIB_OBJECTS) $(MY_LIB_PROJECT_OBJECTS)
+	@rm -f $(MY_OBJECTS) $(MY_LIB_OBJECTS) \
+		$(MY_LIB_PROJECT_OBJECTS) \
+		$(PROJECT_CHECKERS_RESOURCE_OBJECTS) \
+		$(PROJECT_GENERATE_MAP_RESOURCE_OBJECTS) \
+		$(PROJECT_FILE_UTILS_RESOURCE_OBJECTS) \
+		$(PROJECT_MAP_UTILS_RESOURCE_OBJECTS) \
+		$(LIB_MLX_DIR)/*.o
 	@rm -f $(NAME) $(LIB_NAME) $(LIB_PROJECT_NAME)
+	@rm -f $(LIB_MLX_NAME)
 	@if [ $$? -eq 0 ]; then \
-		echo "\033[32mArchivos objeto eliminados correctamente.\033[0m"; \
+		echo "\033[32mLimpieza completa realizada correctamente.\033[0m"; \
 	else \
-		echo "\033[31mError al eliminar los archivos objeto.\033[0m"; \
+		echo "\033[31mError al realizar la limpieza completa.\033[0m"; \
 	fi
 
-re: fclean all
+# Rebuild everything
+re: fclean
+	@echo "\033[34mRecompilando todo...\033[0m"
+	@$(MAKE) --always-make all
+	@if [ $$? -eq 0 ]; then \
+		echo "\033[35mRecompilación finalizada correctamente.\033[0m"; \
+	else \
+		echo "\033[31mError durante la recompilación.\033[0m"; \
+	fi
+
+# Phony targets
 .PHONY: all clean fclean re
